spring:
  application:
    name: backend
    datasource:
      url: jdbc:postgresql://localhost:5432/incidents
      username: user
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: false
  docker:
    compose:
      enabled: true
      file: ../compose.yaml